apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.1.1.18-10.1.1.20 # IP range reserved for the Load balancer
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: tomlab
  namespace: metallb-system
---